# ---------------------------------------------------------------
# Basic
# ---------------------------------------------------------------

# Appearance
appearance:
  # Accent color, default '#2a2b33'
  accent_color:
  # Font color, default '#363636'
  foreground_color:
  # Border color, default '#e0e0e0'
  border_color:
  # body background, default '#f5f7fa'
  background:
  # Sidebar background (when opened), default to accent_color
  sidebar_background:
  # Card background, default '#fff'
  card_background:

  # All background settings above support image, e.g.,
  # '//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png #f5f7fa' or
  # 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'

  # Maximum width of content
  # content_width: 640

  # Fonts
  font:
    # Url of font css file
    # Below is a font set containing Baloo Bhaijaan, Josefin Sans, Montserrat and Inconsolata from Google Fonts.
    url: //fonts.googleapis.com/css?family=Baloo+Bhaijaan|Inconsolata|Josefin+Sans|Montserrat

    # Base font which applied to body
    base: "'Josefin Sans', 'PingFang SC'"
    # Sidebar author font, fallback to `base`
    logo:
    # Sidebar menu font, fallback to `base`
    menu: 'Baloo Bhaijaan'
    # Font for:
    # - percentage on the fab button
    # - month text on archives page
    # - count
    # - pager
    # - toc index
    # - category pill
    # fallback to `base`
    label: Montserrat
    # Headline(h1, h2, h3, h4, h5, h6) font, fallback to `base`
    heading:
    # Code and code block
    code: Inconsolata, monospace
    # Base font for printing which applied to body
    print:

  # Code Syntax Highlighting
  # Uses an architecture called "base16" (https://github.com/chriskempson/base16),
  # the default theme is a customized Atelier Dune Light theme,
  # please feel free to explore more.
  highlight:

  # Default Light by Chris Kempson (http://chriskempson.com)
  # highlight: [
  #   '#f8f8f8', '#e8e8e8', '#d8d8d8', '#b8b8b8',
  #   '#585858', '#383838', '#282828', '#181818',
  #   '#ab4642', '#dc9656', '#f7ca88', '#a1b56c',
  #   '#86c1b9', '#7cafc2', '#ba8baf', '#a16946'
  # ]

  # Harmonic16 Light by Jannik Siebert (https://github.com/janniks)
  # highlight: [
  #   '#f7f9fb', '#e5ebf1', '#cbd6e2', '#aabcce',
  #   '#627e99', '#405c79', '#223b54', '#0b1c2c',
  #   '#bf8b56', '#bfbf56', '#8bbf56', '#56bf8b',
  #   '#568bbf', '#8b56bf', '#bf568b', '#bf5656'
  # ]

  # Tomorrow Night by Chris Kempson (http://chriskempson.com)
  # highlight: [
  #   '#1d1f21', '#282a2e', '#373b41', '#969896',
  #   '#b4b7b4', '#c5c8c6', '#e0e0e0', '#ffffff',
  #   '#cc6666', '#de935f', '#f0c674', '#b5bd68',
  #   '#8abeb7', '#81a2be', '#b294bb', '#a3685a'
  # ]

# Sidebar profile
profile:
  # `email` is used for gravatar(https://en.gravatar.com),
  # fallback to `hexo.config.email` if not specified
  email: z1052525203@outlook.com

  # You can set Avatar URL directly
  avatar: ./avatar.jpg

  bio: Learning how to program an OS.

# Sidebar navigation links
menu:
  Home: /
  Search: /search
  # About: /about
  # Links: /links
  # Github: https://github.com/username

# Social media URL
sns:
  # Built-in icons
  # `email`, `feed`, `github`, `twitter`, `facebook`, `instagram`, `tumblr`, `dribbble`, `telegram`
  # `youtube`, `hangouts`, `linkedin`, `pinterest`, `soundcloud`, `myspace`, `weibo`, `qq`
  - icon: email
    title: Email
    url: z1052525203@outlook.com
  - icon: github
    title: GitHub
    url: https://github.com/superfish

  # custom icon
  # - title: Email me
  #   url: # default to `profile.email`
  #   template: <i class="fa fa-github"></i>
  # - title: Love you
  #   url:
  #   template: |
  #     <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="black" width="18px" height="18px"><path d="M0 0h24v24H0z" fill="none"/><path d="M12 21.35l-1.45-1.32C5.4 15.36 2 12.28 2 8.5 2 5.42 4.42 3 7.5 3c1.74 0 3.41.81 4.5 2.09C13.09 3.81 14.76 3 16.5 3 19.58 3 22 5.42 22 8.5c0 3.78-3.4 6.86-8.55 11.54L12 21.35z"/></svg>

# Sidebar footer copyright info
footer:
  # Set to false to hide.
  # copyright: '&copy; 2019 • <a href="">John Doe</a>'

  # Set to false to hide Hexo link.
  powered: false

  # Set to false to hide theme link.
  theme: false

  # Custom text.
  custom: <a href="https://996.icu"><img src="https://img.shields.io/badge/link-996.icu-red.svg" alt="996.icu" /></a>


# ---------------------------------------------------------------
# Content
# ---------------------------------------------------------------

# Page
page:
  # Display Table of content, default to `true`
  toc: true

  # Display reward, default to `false`
  # reward: true

  # Display copyright notice, default to `false`
  # copyright: true


# Post
post:
  # per_page: 10
  # reading_time: false
  # reading_time:
  #   wpm: 150
  #   text: ":words words in :minutes min"

  # The following settings are the same as the page
  # toc: false
  # reward: true
  # copyright: true

# Archive
archive:
  # per_page: 10

# Tag
tag:
  # per_page: 10

# Category
category:
  # per_page: 10

# Search
search:
  # Display a quick search button in fab
  fab: true
  page: true
  adapter:
    range:
      - post

  # Render a stand

plugins:
  - //unpkg.com/gitalk/dist/gitalk.css
  - //unpkg.com/gitalk/dist/gitalk.min.js
  - position: comments
    template: |
      <div id="gitalk-container"></div>
      <script>
        var gitalk = new Gitalk({
          clientID: 'b098ca1afffa650fcae0',
          clientSecret: '54252a9acacb2a3b4c938a31e2c4794853c163b1',
          repo: 'fishjump.github.io',
          owner: 'fishjump',
          admin: ['fishjump'],
          id: location.href,      // Ensure uniqueness and length less than 50
          distractionFreeMode: false  // Facebook-like distraction free mode
        })
        gitalk.render('gitalk-container')
      </script>